Nginx Ingress values (kubernetes/ingress/nginx-ingress-values.yaml)
controller:
  replicaCount: 2
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  config:
    use-http2: "true"
    ssl-redirect: "true"
    force-ssl-redirect: "true"
    proxy-body-size: "50m"
    keep-alive: "75"
  metrics:
    enabled: true
